use_frameworks!

platform :ios, '8.0'

pod 'AFNetworking'
pod 'SSZipArchive'

target 'DownloadManager_Example' do
  pod 'DownloadManager', :path => '../'

  target 'DownloadManager_Tests' do
    inherit! :search_paths

    
  end
end
